export const BASE_URL = 'http://localhost:8080/api'
export const UPLOAD = '/importacao'
export const OBTER_CANDIDATO_POR_ESTADO = '/pessoas/candidatos-por-estado/'
export const OBTER_IMC_MEDIO_POR_FAIXA_ETARIA = '/pessoas/imc-medio-por-faixa-etaria/'
export const OBTER_DOADORES_POR_RECEPTOR = '/pessoas/doadores-por-receptor/'
export const OBTER_OBESIDADE_POR_SEXO = '/pessoas/obesidade-por-sexo/'
export const OBTER_MEDIA_POR_TIPO_SANGUINEO = '/pessoas/media-por-tipo-sanguineo/'